environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.*"
      PYTHON_ARCH: "64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "echo %PYTHON%"
  # - "python -m pip install --disable-pip-version-check --user --upgrade pip"
  - "pip3 install -e ."
  - "pip3 install -r test-requirements.txt"

build: off

test_script:
  - "python runtests.py"
