language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - python setup.py develop
  - gem install coveralls-lcov
  - pip install -r test-requirements.txt
  - npm install jasmine-core@2.3.4 karma@1.1.2 karma-coverage@1.1.1 karma-jasmine@0.3.8 karma-firefox-launcher@1.0.0 karma-coveralls@1.1.2
  - gem install rake
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - opal test --coverage
after_success:
  - ls -lha coverage
  - coveralls-lcov -v -n coverage/Firefox\ 31.0.0\ \(Linux\ 0.0.0\)/lcov.info > coverage/coverage.json
  - cat coverage/coverage.json
  - coveralls debug --merge=coverage/coverage.json
  - coveralls --merge=coverage/coverage.json
notifications:
  slack: ohcuk:6spaME3CB7f2PGrMAcklYWqp
sudo: false
