site_name: Opal
docs_dir: docs
pages:
  - Home: index.md
  - installation.md
  - Tutorial: tutorial.md
  - Tutorials:
    # Early steps with Opal
    - tutorials/pathway_tutorial.md
    - tutorials/theming_tutorial.md
  - Guides: guides/topic-guides.md
  - Reference: reference/reference_guides.md

  - Topic Guides:
      # Opal
      - Component Overview: guides/components_overview.md
      - Command Line tool: guides/command_line_tool.md
      - Discoverable Features: guides/discoverable.md
      - Plugins: guides/plugins.md
      - Plugin List: guides/plugins_list.md

      # Data and business logic
      - Data Model: guides/datamodel.md
      - Episodes: guides/episodes.md
      - Archetypes: guides/archetypes.md
      - Referencedata: guides/referencedata.md
      - Metadata: guides/metadata.md
      - Angular Models: guides/working_with_data_in_angular.md
      - Flow: guides/flow.md
      - Roles & Permissions: guides/roles_and_permissions.md
      - Tagging: guides/tagging.md
      - JSON API: guides/json_api.md

      # Presentation and templating
      - Theming: guides/theming.md
      - Templates: guides/templates.md
      - Context Processors: guides/context_processors.md
      - Static Files: guides/static_files.md
      - Forms: guides/forms.md
      - Patient Detail Views: guides/patient_detail_views.md
      - Patient List Views: guides/list_views.md

      # Optional components
      - Search Overview: guides/search.md
      - Pathway Overview: guides/pathways.md
      - Django Admin: guides/django_admin.md

      # Working on Opal itself
      - Contributing: guides/CONTRIBUTING.md
      - Development environment: guides/development_environment.md
      - Releasing: guides/releasing.md

      # Other guides
      - Deployment: guides/deployment.md

  - Reference:
      # python
      # Models
      - The Episode model: reference/episode.md
      - The Patient model: reference/patient.md
      - Subrecords: reference/subrecords.md
      - UserProfile: reference/user_profile_model.md
      - Mixins: reference/mixins.md

      # Opal Core
      - OpalApplication: reference/opal_application.md
      - Detail Views: reference/detail_views.md
      - Episode Categories: reference/episode_categories.md
      - Schemas: reference/schemas.md
      - Patient Lists: reference/patient_list.md
      - OpalPlugin: reference/plugin.md
      - Core.Views: reference/core_views.md
      - Menus: reference/core_menus.md
      - Log: reference/loggers.md
      - Fields: reference/core_fields.md
      - Lookuplists: reference/core_lookuplists.md
      - Discoverable: reference/core_discoverable.md

      # Angular Services
      - reference/javascript/patient_service.md
      - reference/javascript/episode_service.md
      - reference/javascript/item_service.md
      - reference/javascript/user_service.md
      - reference/javascript/patient_summary_service.md
      - Search JS Services: reference/javascript/search_js_services.md
      - reference/javascript/loaders.md

      # Helper libraries
      - Form helpers: reference/form_templatetags.md
      - Panel Template tags: reference/panels_templatetags.md
      - Menu Template tag: reference/menus_templatetags.md
      - Javascript helpers: reference/javascript/javascript_helpers.md

      # Search
      - Search Queries: reference/search_queries.md

      # Pathways
      - Pathway: reference/pathways.md

      # Misc
      - Settings: reference/settings.md
      - Changelog: reference/CHANGELOG.md
      - Testing: reference/testing.md
      - Javascript dependencies: reference/javascript/javascript_dependencies.md
      - Upgrading: reference/upgrading.md
      - Management commands: reference/management_commands.md



theme: mkdocs
theme: cerulean
theme: cosmo
theme_dir: 'custom_theme'


dev_addr: 0.0.0.0:8965
include_next_prev: false

extra:
  version: v0.10.0

markdown_extensions:
    - fenced_code
