site_name: OPAL
docs_dir: docs
pages:
  - Home: index.md
  - installation.md
  - tutorial.md
  - Guides: guides/topic-guides.md
  - Reference: reference/reference_guides.md

  - Topic Guides:
      - Component Overview: guides/components_overview.md
      - Command Line tool: guides/command_line_tool.md
      - Plugins: guides/plugins.md
      - Plugin List: guides/plugins_list.md
      - Data Model: guides/datamodel.md
      - Archetypes: guides/archetypes.md
      - Angular Models: guides/working_with_data_in_angular.md
      - Flow: guides/flow.md
      - Roles & Permissions: guides/roles_and_permissions.md
      - Tagging: guides/tagging.md
      - JSON API: guides/json_api.md
      - Lookup Lists: guides/lookup_lists.md
      - Templates: guides/templates.md
      - Context Processors: guides/context_processors.md
      - Static Files: guides/static_files.md
      - Forms: guides/forms.md
      - Patient Detail Views: guides/patient_detail_views.md
      - Patient List Views: guides/list_views.md
      - Discoverable Features: guides/discoverable.md
      - Search Overview: guides/search.md

  - Reference:
      - The Episode model: reference/episode.md
      - Episode Categories: reference/episode_categories.md
      - reference/patient.md
      - Subrecords: reference/subrecords.md
      - OpalApplication: reference/opal_application.md
      - reference/episode_service.md
      - reference/item_service.md
      - reference/patient_summary_service.md
      - Form helpers: reference/form_templatetags.md
      - Panel Template tags: reference/panels_templatetags.md
      - Javascript helpers: reference/javascript_helpers.md
      - Javascript dependencies: reference/javascript_dependencies.md
      - Schemas: reference/schemas.md
      - Search Queries: reference/search_queries.md
      - Detail Views: reference/detail_views.md
      - Patient Lists: reference/patient_list.md
      - Search JS Services: reference/search_js_services.md
      - Changelog: reference/changelog.md
      - Upgrading: reference/upgrading.md

theme: mkdocs
theme: cerulean
theme: cosmo
theme_dir: 'custom_theme'


dev_addr: 0.0.0.0:8965
include_next_prev: false

extra:
  version: v0.7.1

markdown_extensions:
    - fenced_code
